```{r}
library(caret)
library(splitTools)
```
```{r}
data1 =read.csv("data1.csv")
data1[data1$UHRSWORKT == 999,]$UHRSWORKT=0
data1 <- data1 %>%
  filter(UHRSWORKT!=997)
```
```{r}
data1
```

```{r}
train <- subset(data1, YEAR>=2017 & YEAR <= 2018) 
valid =subset(data1 , YEAR==2019)
#train_1=sample_n(data1,100000)
```
```{r}
train_1=sample_n(train,100000)
```
```{r}
set.seed(3451)
inds <- partition(train_1$INCTOT, p = c(train = 0.8, test = 0.2))
training <- train_1[inds$train, ]
testing <- train_1[inds$test, ]
```
```{r}
K_values <- c(2:50)
RMSE <- c()
```
```{r}
for (i in K_values){
#run KNN models
knn = knnreg(INCTOT ~ HEALTH + EDUC + EMPSTAT + UHRSWORKT + RACE + OCC + CITIZEN+ AGE + MARST + STATEFIP + SEX, data = training, k=i)
  #made a vector of RMSE values
  e <- modelr::rmse(knn,testing)
  RMSE <- c(RMSE,e)
}
RMSE
```
```{r}
k_opt=2+which.min(RMSE)
knn = knnreg(INCTOT ~ HEALTH + EDUC + EMPSTAT + UHRSWORKT + RACE + OCC + CITIZEN+ AGE + MARST + STATEFIP + SEX, data = train_1, k=k_opt)
e <- modelr::rmse(knn,valid)
```

```{r}
print(paste0("The RMSE of CART model on test data is: ",e))
```
```{r}
covid_year=subset(data1 , YEAR==2020)
print(paste0("The RMSE of CART model for the year 2020 is: ",modelr::rmse(knn,covid_year)))
```
