---
title: "Random_Forest"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ranger)
library(splitTools)
library(dplyr)
data1 =read.csv("C:\\Users\\sachd\\Documents\\Economics phd\\Applications\\UT Austin\\Spring 2023\\Data Mining\\Project\\Data set\\data1.csv")
data1[data1$UHRSWORKT == 999,]$UHRSWORKT=0
data1 <- data1 %>% filter(UHRSWORKT!=997)
train <- subset(data1, YEAR>=2017 & YEAR <= 2018) 
valid =subset(data1 , YEAR==2019)
train_1=sample_n(train,100000)
set.seed(3451)
inds <- partition(train_1$INCTOT, p = c(train = 0.8, test = 0.2))
training <- train_1[inds$train, ]
testing <- train_1[inds$test, ]
rmse <- function(y, pred) {
  sqrt(mean((y - pred)^2))
}
valid_mtry <- numeric(11)
for (i in seq_along(valid_mtry)) {
  cv_mtry <- numeric()
    fit <- ranger(INCTOT ~ HEALTH + EDUC + EMPSTAT + UHRSWORKT + RACE + OCC + CITIZEN+ AGE + MARST + STATEFIP + SEX, data = training, mtry = i)
    cv_mtry <- c(cv_mtry,rmse(testing$INCTOT, predict(fit, testing)$predictions))
  valid_mtry[i] <- mean(cv_mtry)
}
valid_mtry
# finding the best hyper parameter (that gave the least RMSE)
best_mtry <- which.min(valid_mtry)
# checking RMSE of the random forest model with the best hyper parameter on test data
final_fit <- ranger(INCTOT ~ HEALTH + EDUC + EMPSTAT + UHRSWORKT + RACE + OCC + CITIZEN+ AGE + MARST + STATEFIP + SEX, data = train_1, mtry = best_mtry)
print(paste0("The RMSE of Random Forest model on test data is: ",rmse(valid$INCTOT, predict(final_fit, valid)$predictions)))
covid_year=subset(data1 , YEAR==2020)
print(paste0("The RMSE of Random Forest for the year 2020 is: ",rmse(covid_year$INCTOT, predict(final_fit, covid_year)$predictions)))
```
